### ISSUE TITLE
Not working with gitbook 1.5.0

### ISSUE THREAD

**Issue by prateekbaheti** [erixtekila/gitbook-plugin-richquotes#12]
Added a note ```> **Note** Note text```. The plugin is installed and added and configured in books.json.
````
  "plugins": [
        "richquotes"
    ],
    "pluginsConfig": {
        "richquotes": {
            "Info": true,
            "Hint": true,
            "Note": true,
            "Comment": true,
            "Caution": true,
            "Danger": true
        }
````
It renders only as a simple markdown blockquote.

**Comment by erixtekila** [comment]
Are you sure you've added the plugin to the package.son file and install it ?
It worked for me on this gitbook version.
