### ISSUE TITLE
Use GitBook 2.0 block tags?

### ISSUE THREAD

**Issue by leesei** [erixtekila/gitbook-plugin-richquotes#13]
What do you think of using block tags instead of hacking \`\`\`?
The quote type will be one of the parameter and would not interfere with the content of the quote.

```md
> **Info** Info quotes
```
to 
```md
{% richquotes info %}
Info quotes
{% endrichquotes %}
```

Optionally we can strip `/$>[\s]*/` to accept this:
```md
{% richquotes info %}
> Info quotes
{% endrichquotes %}
```
(I think the Github parser parsed it wrongly.)

**Comment by erixtekila** [comment]
That may be good idea.
I ddin't get the time to read the last plugins features. WIll check that.

**Comment by leesei** [comment]
I did an experiment.

```md
{% myTag %}*World*{% endmyTag %}
```
yields
```
Hello *World*
```

The content is not passed to Markdown pipeline so we can no longer use Markdown.
We have to use HTML tags unless we're parsing `blk.body` in the handler.
```md
{% myTag %}<i>World</i>{% endmyTag %}
```

I would open a issue on GitBook to discuss the merits of template block tags.

**Comment by glueckpress** [comment]
+1 for what @leesei says, Markdown inside of block level HTML elements [will not be parsed](https://daringfireball.net/projects/markdown/syntax):

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style *emphasis* inside an HTML block.

As attractive as block level elements seem for common use cases of this plugin, I think they justify another plugin rather than modifying this one.
