### ISSUE TITLE
User defined tag

### ISSUE THREAD

**Issue by leesei** [erixtekila/gitbook-plugin-richquotes#14]
Allow user to define tags in config:

```json
"pluginsConfig":
{
    "richquotes" : {
        "star" : {
            "alert": "warning",
            "picto": "fa-star"
        }
    }
}
```

**Comment by leesei** [comment]
Please check my branch at [leesei/gitbook-plugin-richquotes](https://github.com/leesei/gitbook-plugin-richquotes).

Now that user can define annotations, I think we can trim down the built-in ones.
Please comment before I submit PR.

**Comment by leesei** [comment]
Any comments on this?

**Comment by erixtekila** [comment]
Sorry, no time now.

**Comment by glueckpress** [comment]
My javascript is not far from superb, but @leesei’s code looks decent to me there, and it obviously solves a potential issue with localization. Currently I cannot use the plugin in another language than English; with @leesei’s branch I can. Would love to see it merged.

**Comment by leesei** [comment]
I'm thinking of pushing my repo to NPM.
Anyone interested can use 
```sh
npm install https://github.com/leesei/gitbook-plugin-richquotes
```
to use my branch.

**Comment by erixtekila** [comment]
Sorry for the delay @leesei 
I've look after your proposals. Why don't you send a PR, I'll update the repo.

**Comment by leesei** [comment]
'K.

**Comment by glueckpress** [comment]
@leesei Thank you! 
@erixtekila For the record, meanwhile GitBook may have started working on a similar plugin. Slack archive URL for reference: https://gitbook-community.slack.com/archives/general/p1443713075000136.
