### ISSUE TITLE
Consecutive quotes not separated

### ISSUE THREAD

**Issue by orlade** [erixtekila/gitbook-plugin-richquotes#19]
Given the text:

```md
> **Note** Note

> **Tag** Tag
```
The note and tag quotes will run together like this:

![image](https://cloud.githubusercontent.com/assets/4531277/11173349/4e5864e0-8c69-11e5-9659-8591c1dbcdbc.png)

Multiple empty lines doesn't help.

With a paragraph in between to separate them, the result is as expected:

![image](https://cloud.githubusercontent.com/assets/4531277/11173356/62a4fc9c-8c69-11e5-8ae5-4de0d01927e5.png)

**Comment by erixtekila** [comment]
It's a known issue that inherits from markdown quotes.
You'd use seprators like paragrahs

**Comment by show0k** [comment]
As it is a common issue, you could maybe advise users on the readme, and talk about the paragrah separator tip.
