### ISSUE TITLE
blockquote, p > strong strong, not supported

### ISSUE THREAD

**Issue by anibalsanchez** [erixtekila/gitbook-plugin-richquotes#6]
Hi,

If there's more strong text in the paragraph (beyond the richquote declaration), then richquotes are disabled and it just outputs 

<blockquote><p><strong>Warning</strong> ... <strong>more</strong> ... </blockquote>

That's beause $strong.text().toLowerCase() concatenates all strongs (warningmore), thus a richquote, such as Warning, can't be detected.

Please, add a note to document the limitation. (It was driving me crazy ;-) )

Thanks!

**Comment by aschempp** [comment]
I guess this can be closed as PR #7 has been merged :-)

**Comment by erixtekila** [comment]
yep, you're right

**Comment by leesei** [comment]
FYI, the update code was not pushed to NPM.

**Comment by erixtekila** [comment]
@leesei I'll doucble check this. Thanks.
